### ISSUE TITLE
prep.py column issue

### ISSUE THREAD

**Issue by streamside7** [ichibod/object-detection-for-coreml#2]
I receive the following error when running prep.py:
```

Traceback (most recent call last):
  File "prep.py", line 33, in <module>
    data['annotations'] = SArray(data=annotations, dtype=list)
  File "/home/rpinglet/venv/local/lib/python2.7/site-packages/turicreate/data_structures/sframe.py", line 3585, in __setitem__
    self.add_column(sa_value, key, inplace=True)
  File "/home/rpinglet/venv/local/lib/python2.7/site-packages/turicreate/cython/context.py", line 49, in __exit__
    raise exc_type(exc_value)
RuntimeError: Column "annotations" has different size than current columns!
```

I used the Simple Image Annotator, which worked well. The convert.py also seems to have worked as expected. Is there a change that needs to be made to annotations after convert.py has completed?

**Comment by streamside7** [comment]
It seems I left the header in the csv file. Removing the header line fixed this issue.

**Comment by streamside7** [comment]
Actually this was not the issue

**Comment by streamside7** [comment]
This seems to happen when there is a line in the CSV file which doesn't have a corresponding image file. Make sure there is a corresponding image file for every line in the CSV file.
